version: 0.1
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g serverless
  build:
    commands:
      - echo Deploying...
      - serverless deploy --stage ${DeployStage}
      - echo Done
