version: 0.1
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g serverless
      - npm install serverless-domain-manager --save-dev
  build:
    commands:
      - serverless deploy --stage ${DeployStage}
